Lesson 1
thetribalme/Python_bases pull request #1
Opened 2023-05-18 17:58 UTC by thetribalme

2023-05-19 11:58 UTC, IrinaMilekhina requested changes

2023-05-19 11:58 UTC, IrinaMilekhina commented on Lesson_1/Lesson_1.2.py
> +added_amount = 17    # число, которое надо добавить к эелемнтам списка
опечатка в комментарии

2023-05-19 11:58 UTC, IrinaMilekhina commented on Lesson_1/Lesson_1.2.py
> +    tmp = number % 2 > 0
лучше назвать переменную осмысленно, например проверка_нечетности

2023-05-19 11:58 UTC, IrinaMilekhina commented on Lesson_1/Lesson_1.2.py
> +for number in range(list_till):
тут можно сделать удобнее, если использовать остальные аргументы range, посмотри, что он умеет и попробуй сократить код

2023-05-19 11:58 UTC, IrinaMilekhina commented on Lesson_1/Lesson_1.2.py
> +for idx in range(len(odd_list)):
почему идет итерация по индексам, а не по элементам?

2023-05-19 11:58 UTC, IrinaMilekhina commented on Lesson_1/Lesson_1.2.py
> +for idx in range(len(odd_list)):
почему идет итерация по индексам, а не по элементам?

2023-05-19 11:58 UTC, IrinaMilekhina commented on Lesson_1/Lesson_1.2.py
> +for idx in range(len(odd_list)):
тот же вопрос-наводка про индексы

2023-05-19 11:58 UTC, IrinaMilekhina commented on Lesson_1/Lesson_1.3.py
> +word_ending = {
попробуй написать реализацию через if, она будет достаточно простой если использовать логические операторы

2023-05-19 11:58 UTC, IrinaMilekhina commented on Lesson_1/Lesson_1.3.py
> +for idx in range(list_till):
нам точно нужен этот цикл?

2023-05-19 11:58 UTC, IrinaMilekhina commented on Lesson_1/Lesson_1.3.py
> +idx = 0
зачем эта переменная?

2023-05-19 11:58 UTC, IrinaMilekhina commented on Lesson_1/Lesson_1.3.py
> +    tmp = number_list[idx] % 10
осмысленное название переменной
tmp можно назвать когда ты отлаживаешься, например, но в итоговой версии кода такого следует избегать

2023-05-19 12:37 UTC, IrinaMilekhina commented on Lesson_1/Lesson_1.3.py
> +    0: "ов",
можно ли сделать этот словарь короче? подумай над структурой

2023-05-22 13:35 UTC, thetribalme commented on Lesson_1/Lesson_1.2.py
> +added_amount = 17    # число, которое надо добавить к эелемнтам списка
опечатка исправлена

2023-05-22 15:08 UTC, thetribalme commented on Lesson_1/Lesson_1.2.py
> +for number in range(list_till):
Использовала аргументы "начало" и "шаг", и правда получилось короче)

2023-05-22 15:08 UTC, thetribalme commented on Lesson_1/Lesson_1.2.py
> +    tmp = number % 2 > 0
Переменная исчезла при оптимизации по предыдущему пункту

2023-05-22 15:25 UTC, thetribalme commented on Lesson_1/Lesson_1.2.py
> +for idx in range(len(odd_list)):
Исправила

2023-05-22 15:32 UTC, thetribalme commented on Lesson_1/Lesson_1.2.py
> +for idx in range(len(odd_list)):
Исправила

2023-05-22 15:32 UTC, thetribalme commented on Lesson_1/Lesson_1.2.py
> +for idx in range(len(odd_list)):
Исправила

2023-05-22 15:56 UTC, thetribalme commented on Lesson_1/Lesson_1.3.py
> +idx = 0
Удалила

2023-05-22 16:36 UTC, thetribalme commented on Lesson_1/Lesson_1.3.py
> +word_ending = {
Добавила и такой вариант

2023-05-22 16:38 UTC, thetribalme commented on Lesson_1/Lesson_1.3.py
> +    tmp = number_list[idx] % 10
переменная переименована

2023-05-22 18:29 UTC, IrinaMilekhina approved these changes

2023-05-22 18:43 UTC, merged